services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_NAME=portfolio
    networks:
      - spring-postgres
    volumes:
      - ./backend/logs:/app/logs
  frontend:
    build: ./frontend
    ports:
      - 4200:4200
    networks:
      - spring-postgres
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
    - ./backend/db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - DB_NAME=portfolio
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
secrets:
  db-password:
    file: db/password.txt
networks:
  spring-postgres:
